name = "inventer-checker"
main = "src/index.js"
compatibility_date = "2026-07-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[ai]
binding = "AI"

[[rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = true
